#!/bin/bash

# ZSH
# Check if zsh is installed
if [[ ! $(which zsh) ]]
then 
    echo "zsh is not installed. Install it, and run this script again"
else
    # Ask if user wants to overwrite .zshrc (only if it exists already)
    if [[ -f ~/.zshrc ]]
    then
        read -p "Do you want to overwrite your current ~/.zshrc [Y/n] "
        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            rm ~/.zshrc
            ln -s ~/Dotfiles/.zshrc ~/.zshrc
	    source ~/.zshrc
        fi
    else
	rm ~/.zshrc
        ln -s ~/Dotfiles/.zshrc ~/.zshrc
        source ~/.zshrc
    fi

    # Check if oh my zsh (plugin manager for zsh) is installed
    if [[ ! -d  ~/.oh-my-zsh ]]
    then
        read -p "Do you want to install oh-my-zsh? [Y/n] "
        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            echo "Installing the plugin manager oh-my-zsh..."
            sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi
    fi

    # Check if the custom plugin auto-suggestions is already installed
    if [[ ! -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]]
    then
        read -p "Do you want to install the plugin zsh-autosuggestions? [Y/n] "
        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        fi
    fi

    # Check if the custom plugin zsh-syntax-highlighting is already installed
    if [[ ! -d ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]]
    then
        read -p "Do you want to install the plugin zsh-syntax-highlighting? [Y/n] "
        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        fi
    fi
fi

# VIM
# Check if vim is installed
if [[ ! $(which vim) ]]
then
    echo "vim is not installed. Install it, and run this script again"
else
    # Ask if user wants to overwrite .vimrc (only if it exists already)
    if [[ -f ~/.vimrc ]]
    then
        read -p "Do you want to overwrite your current ~/.vimrc [Y/n] "
        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            rm ~/.vimrc
            ln -s ~/Dotfiles/.vimrc ~/.vimrc
        fi
    else
	rm ~/.vimrc
        ln -s ~/Dotfiles/.vimrc ~/.vimrc
    fi

    # Check if vim-plug is already installed
    if [[ ! -d ~/.vim/plugged ]]
    then
        read -p "Do you want to install vim plugins? [Y/n] "

        if [[ $REPLY =~ ^[Yy]$ ]]
        then 
            curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
            echo "Rembember to run ':PlugInstall' the first time when using vim"
        fi
    fi
fi
